"""Vanilla item at each location (generated from zsrtp Web Generator checks).

Used to build the "your vanilla item is actually at ..." hints in slot_data.
Item names not in ITEM_TABLE (story items etc.) are kept verbatim for display.
"""

VANILLA_ITEMS: dict[str, str] = {
    'Agitha Female Ant Reward': 'Purple Rupee',
    'Agitha Female Beetle Reward': 'Purple Rupee',
    'Agitha Female Butterfly Reward': 'Purple Rupee',
    'Agitha Female Dayfly Reward': 'Orange Rupee',
    'Agitha Female Dragonfly Reward': 'Orange Rupee',
    'Agitha Female Grasshopper Reward': 'Orange Rupee',
    'Agitha Female Ladybug Reward': 'Orange Rupee',
    'Agitha Female Mantis Reward': 'Orange Rupee',
    'Agitha Female Phasmid Reward': 'Orange Rupee',
    'Agitha Female Pill Bug Reward': 'Purple Rupee',
    'Agitha Female Snail Reward': 'Purple Rupee',
    'Agitha Female Stag Beetle Reward': 'Orange Rupee',
    'Agitha Male Ant Reward': 'Orange Rupee',
    'Agitha Male Beetle Reward': 'Orange Rupee',
    'Agitha Male Butterfly Reward': 'Orange Rupee',
    'Agitha Male Dayfly Reward': 'Purple Rupee',
    'Agitha Male Dragonfly Reward': 'Purple Rupee',
    'Agitha Male Grasshopper Reward': 'Progressive Wallet',
    'Agitha Male Ladybug Reward': 'Purple Rupee',
    'Agitha Male Mantis Reward': 'Purple Rupee',
    'Agitha Male Phasmid Reward': 'Progressive Wallet',
    'Agitha Male Pill Bug Reward': 'Orange Rupee',
    'Agitha Male Snail Reward': 'Purple Rupee',
    'Agitha Male Stag Beetle Reward': 'Purple Rupee',
    'Arbiters Grounds Big Key Chest': 'Arbiters Grounds Big Key',
    'Arbiters Grounds Death Sword Chest': 'Spinner',
    'Arbiters Grounds Dungeon Reward': 'Progressive Mirror Shard',
    'Arbiters Grounds East Lower Turnable Redead Chest': 'Arbiters Grounds Small Key',
    'Arbiters Grounds East Turning Room Poe': 'Poe Soul',
    'Arbiters Grounds East Upper Turnable Chest': 'Arbiters Grounds Compass',
    'Arbiters Grounds East Upper Turnable Redead Chest': 'Arbiters Grounds Small Key',
    'Arbiters Grounds Entrance Chest': 'Arbiters Grounds Small Key',
    'Arbiters Grounds Ghoul Rat Room Chest': 'Arbiters Grounds Small Key',
    'Arbiters Grounds Hidden Wall Poe': 'Poe Soul',
    'Arbiters Grounds North Turning Room Chest': 'Arbiters Grounds Small Key',
    'Arbiters Grounds Spinner Room First Small Chest': 'Bombs (10)',
    'Arbiters Grounds Spinner Room Lower Central Small Chest': 'Yellow Rupee',
    'Arbiters Grounds Spinner Room Lower North Chest': 'Yellow Rupee',
    'Arbiters Grounds Spinner Room Second Small Chest': 'Red Rupee',
    'Arbiters Grounds Spinner Room Stalfos Alcove Chest': 'Piece of Heart',
    'Arbiters Grounds Stallord': 'Stallord Defeated',
    'Arbiters Grounds Stallord Heart Container': 'Heart Container',
    'Arbiters Grounds Torch Room East Chest': 'Piece of Heart',
    'Arbiters Grounds Torch Room Poe': 'Poe Soul',
    'Arbiters Grounds Torch Room West Chest': 'Arbiters Grounds Map',
    'Arbiters Grounds West Chandelier Chest': 'Red Rupee',
    'Arbiters Grounds West Poe': 'Poe Soul',
    'Arbiters Grounds West Small Chest Behind Block': 'Red Rupee',
    'Arbiters Grounds West Stalfos Northeast Chest': 'Bombs (5)',
    'Arbiters Grounds West Stalfos West Chest': 'Bombs (5)',
    'Ashei Sketch': "Ashei's Sketch",
    'Auru Gift To Fyer': "Auru's Memo",
    'Barnes Bomb Bag': 'Bomb Bag',
    'Bridge of Eldin Female Phasmid': 'Female Phasmid',
    'Bridge of Eldin Male Phasmid': 'Male Phasmid',
    'Bridge of Eldin Owl Statue Chest': 'Piece of Heart',
    'Bridge of Eldin Owl Statue Sky Character': 'Progressive Sky Book',
    'Bulblin Camp First Chest Under Tower At Entrance': 'Arrows (20)',
    'Bulblin Camp Poe': 'Poe Soul',
    'Bulblin Camp Roasted Boar': 'Piece of Heart',
    'Bulblin Camp Small Chest in Back of Camp': 'Purple Rupee',
    'Bulblin Guard Key': 'Gerudo Desert Bublin Camp Key',
    'Castle Town Malo Mart Magic Armor': 'Magic Armor',
    'Cats Hide and Seek Minigame': 'Piece of Heart',
    'Cave of Ordeals Floor 17 Poe': 'Poe Soul',
    'Cave of Ordeals Floor 33 Poe': 'Poe Soul',
    'Cave of Ordeals Floor 44 Poe': 'Poe Soul',
    'Cave of Ordeals Great Fairy Reward': 'Great Fairy Tears (Jovani)',
    'Charlo Donation Blessing': 'Piece of Heart',
    'City in The Sky Aeralfos Chest': 'Progressive Clawshot',
    'City in The Sky Argorok': 'Argorok Defeated',
    'City in The Sky Argorok Heart Container': 'Heart Container',
    'City in The Sky Baba Tower Alcove Chest': 'Piece of Heart',
    'City in The Sky Baba Tower Narrow Ledge Chest': 'Red Rupee',
    'City in The Sky Baba Tower Top Small Chest': 'Yellow Rupee',
    'City in The Sky Big Key Chest': 'City in The Sky Big Key',
    'City in The Sky Central Outside Ledge Chest': 'Red Rupee',
    'City in The Sky Central Outside Poe Island Chest': 'Purple Rupee',
    'City in The Sky Chest Behind North Fan': 'Purple Rupee',
    'City in The Sky Chest Below Big Key Chest': 'Red Rupee',
    'City in The Sky Dungeon Reward': 'Progressive Mirror Shard',
    'City in The Sky East First Wing Chest After Fans': 'City in The Sky Map',
    'City in The Sky East Tile Worm Small Chest': 'Yellow Rupee',
    'City in The Sky East Wing After Dinalfos Alcove Chest': 'Red Rupee',
    'City in The Sky East Wing After Dinalfos Ledge Chest': 'Purple Rupee',
    'City in The Sky East Wing Lower Level Chest': 'City in The Sky Compass',
    'City in The Sky Garden Island Poe': 'Poe Soul',
    'City in The Sky Poe Above Central Fan': 'Poe Soul',
    'City in The Sky Underwater East Chest': 'Red Rupee',
    'City in The Sky Underwater West Chest': 'Water Bombs (15)',
    'City in The Sky West Garden Corner Chest': 'Red Rupee',
    'City in The Sky West Garden Ledge Chest': 'Piece of Heart',
    'City in The Sky West Garden Lone Island Chest': 'Purple Rupee',
    'City in The Sky West Garden Lower Chest': 'Bombs (5)',
    'City in The Sky West Wing Baba Balcony Chest': 'Arrows (20)',
    'City in The Sky West Wing First Chest': 'City in The Sky Small Key',
    'City in The Sky West Wing Narrow Ledge Chest': 'Red Rupee',
    'City in The Sky West Wing Tile Worm Chest': 'Bombs (10)',
    'Coro Bottle': 'Lantern Oil (Coro Bottle)',
    'Death Mountain Alcove Chest': 'Piece of Heart',
    'Death Mountain Trail Poe': 'Poe Soul',
    'Doctors Office Balcony Chest': 'Red Rupee',
    'East Castle Town Bridge Poe': 'Poe Soul',
    'Eldin Field Bomb Rock Chest': 'Piece of Heart',
    'Eldin Field Bomskit Grotto Lantern Chest': 'Purple Rupee',
    'Eldin Field Bomskit Grotto Left Chest': 'Purple Rupee',
    'Eldin Field Female Grasshopper': 'Female Grasshopper',
    'Eldin Field Male Grasshopper': 'Male Grasshopper',
    'Eldin Field Stalfos Grotto Left Small Chest': 'Bombs (5)',
    'Eldin Field Stalfos Grotto Right Small Chest': 'Bombs (5)',
    'Eldin Field Stalfos Grotto Stalfos Chest': 'Piece of Heart',
    'Eldin Field Water Bomb Fish Grotto Chest': 'Purple Rupee',
    'Eldin Lantern Cave First Chest': 'Red Rupee',
    'Eldin Lantern Cave Lantern Chest': 'Piece of Heart',
    'Eldin Lantern Cave Poe': 'Poe Soul',
    'Eldin Lantern Cave Second Chest': 'Purple Rupee',
    'Eldin Spring Underwater Chest': 'Piece of Heart',
    'Eldin Stockcave Lantern Chest': 'Orange Rupee',
    'Eldin Stockcave Lowest Chest': 'Piece of Heart',
    'Eldin Stockcave Upper Chest': 'Red Rupee',
    'Faron Field Bridge Chest': 'Orange Rupee',
    'Faron Field Corner Grotto Left Chest': 'Red Rupee',
    'Faron Field Corner Grotto Rear Chest': 'Yellow Rupee',
    'Faron Field Corner Grotto Right Chest': 'Red Rupee',
    'Faron Field Female Beetle': 'Female Beetle',
    'Faron Field Male Beetle': 'Male Beetle',
    'Faron Field Poe': 'Poe Soul',
    'Faron Field Tree Heart Piece': 'Piece of Heart',
    'Faron Mist Cave Lantern Chest': 'Piece of Heart',
    'Faron Mist Cave Open Chest': 'North Faron Woods Gate Key',
    'Faron Mist North Chest': 'Yellow Rupee',
    'Faron Mist Poe': 'Poe Soul',
    'Faron Mist South Chest': 'Purple Rupee',
    'Faron Mist Stump Chest': 'Red Rupee',
    'Faron Woods Golden Wolf': 'Progressive Hidden Skill',
    'Faron Woods Owl Statue Chest': 'Piece of Heart',
    'Faron Woods Owl Statue Sky Character': 'Progressive Sky Book',
    'Fishing Hole Bottle': 'Empty Bottle (Fishing Hole)',
    'Fishing Hole Heart Piece': 'Piece of Heart',
    'Flight By Fowl Fifth Platform Chest': 'Yellow Rupee',
    'Flight By Fowl Fourth Platform Chest': 'Red Rupee',
    'Flight By Fowl Ledge Poe': 'Poe Soul',
    'Flight By Fowl Second Platform Chest': 'Piece of Heart',
    'Flight By Fowl Third Platform Chest': 'Purple Rupee',
    'Flight By Fowl Top Platform Reward': 'Orange Rupee',
    'Forest Temple Big Baba Key': 'Forest Temple Small Key',
    'Forest Temple Big Key Chest': 'Forest Temple Big Key',
    'Forest Temple Central Chest Behind Stairs': 'Red Rupee',
    'Forest Temple Central Chest Hanging From Web': 'Forest Temple Compass',
    'Forest Temple Central North Chest': 'Forest Temple Map',
    'Forest Temple Diababa': 'Diababa Defeated',
    'Forest Temple Diababa Heart Container': 'Heart Container',
    'Forest Temple Dungeon Reward': 'Progressive Fused Shadow',
    'Forest Temple East Tile Worm Chest': 'Red Rupee',
    'Forest Temple East Water Cave Chest': 'Yellow Rupee',
    'Forest Temple Entrance Vines Chest': 'Yellow Rupee',
    'Forest Temple Gale Boomerang': 'Gale Boomerang',
    'Forest Temple North Deku Like Chest': 'Forest Temple Small Key',
    'Forest Temple Second Monkey Under Bridge Chest': 'Yellow Rupee',
    'Forest Temple Totem Pole Chest': 'Forest Temple Small Key',
    'Forest Temple West Deku Like Chest': 'Piece of Heart',
    'Forest Temple West Tile Worm Chest Behind Stairs': 'Piece of Heart',
    'Forest Temple West Tile Worm Room Vines Chest': 'Red Rupee',
    'Forest Temple Windless Bridge Chest': 'Forest Temple Small Key',
    'Gerudo Desert Campfire East Chest': 'Purple Rupee',
    'Gerudo Desert Campfire North Chest': 'Red Rupee',
    'Gerudo Desert Campfire West Chest': 'Arrows (10)',
    'Gerudo Desert East Canyon Chest': 'Red Rupee',
    'Gerudo Desert East Poe': 'Poe Soul',
    'Gerudo Desert Female Dayfly': 'Female Dayfly',
    'Gerudo Desert Golden Wolf': 'Progressive Hidden Skill',
    'Gerudo Desert Lone Small Chest': 'Arrows (10)',
    'Gerudo Desert Male Dayfly': 'Male Dayfly',
    'Gerudo Desert North Peahat Poe': 'Poe Soul',
    'Gerudo Desert North Small Chest Before Bulblin Camp': 'Arrows (10)',
    'Gerudo Desert Northeast Chest Behind Gates': 'Red Rupee',
    'Gerudo Desert Northwest Chest Behind Gates': 'Red Rupee',
    'Gerudo Desert Owl Statue Chest': 'Orange Rupee',
    'Gerudo Desert Owl Statue Sky Character': 'Progressive Sky Book',
    'Gerudo Desert Peahat Ledge Chest': 'Red Rupee',
    'Gerudo Desert Poe Above Cave of Ordeals': 'Poe Soul',
    'Gerudo Desert Rock Grotto First Poe': 'Poe Soul',
    'Gerudo Desert Rock Grotto Lantern Chest': 'Orange Rupee',
    'Gerudo Desert Rock Grotto Second Poe': 'Poe Soul',
    'Gerudo Desert Skulltula Grotto Chest': 'Orange Rupee',
    'Gerudo Desert South Chest Behind Wooden Gates': 'Orange Rupee',
    'Gerudo Desert West Canyon Chest': 'Purple Rupee',
    'Gift From Ralis': 'Progressive Fishing Rod',
    'Goron Mines After Crystal Switch Room Magnet Wall Chest': 'Piece of Heart',
    'Goron Mines Beamos Room Chest': 'Goron Mines Compass',
    'Goron Mines Chest Before Dangoro': 'Yellow Rupee',
    'Goron Mines Crystal Switch Room Small Chest': 'Red Rupee',
    'Goron Mines Crystal Switch Room Underwater Chest': 'Goron Mines Small Key',
    'Goron Mines Dangoro Chest': "Progressive Hero's Bow",
    'Goron Mines Dungeon Reward': 'Progressive Fused Shadow',
    'Goron Mines Entrance Chest': 'Red Rupee',
    'Goron Mines Fyrus': 'Fyrus Defeated',
    'Goron Mines Fyrus Heart Container': 'Heart Container',
    'Goron Mines Gor Amato Chest': 'Goron Mines Map',
    'Goron Mines Gor Amato Key Shard': 'Goron Mines Key Shard',
    'Goron Mines Gor Amato Small Chest': 'Red Rupee',
    'Goron Mines Gor Ebizo Chest': 'Yellow Rupee',
    'Goron Mines Gor Ebizo Key Shard': 'Goron Mines Key Shard',
    'Goron Mines Gor Liggs Chest': 'Purple Rupee',
    'Goron Mines Gor Liggs Key Shard': 'Goron Mines Key Shard',
    'Goron Mines Magnet Maze Chest': 'Piece of Heart',
    'Goron Mines Main Magnet Room Bottom Chest': 'Goron Mines Small Key',
    'Goron Mines Main Magnet Room Top Chest': 'Purple Rupee',
    'Goron Mines Outside Beamos Chest': 'Goron Mines Small Key',
    'Goron Mines Outside Clawshot Chest': 'Purple Rupee',
    'Goron Mines Outside Underwater Chest': 'Purple Rupee',
    'Goron Springwater Rush': 'Piece of Heart',
    'Herding Goats Reward': 'Piece of Heart',
    'Hidden Village Poe': 'Poe Soul',
    'Hyrule Castle Big Key Chest': 'Hyrule Castle Big Key',
    'Hyrule Castle East Wing Balcony Chest': 'Yellow Rupee',
    'Hyrule Castle East Wing Boomerang Puzzle Chest': 'Hyrule Castle Map',
    'Hyrule Castle Ganondorf': 'Ganondorf Defeated',
    'Hyrule Castle Graveyard Grave Switch Room Back Left Chest': 'Red Rupee',
    'Hyrule Castle Graveyard Grave Switch Room Front Left Chest': 'Green Rupee',
    'Hyrule Castle Graveyard Grave Switch Room Right Chest': 'Orange Rupee',
    'Hyrule Castle Graveyard Owl Statue Chest': 'Hyrule Castle Small Key',
    'Hyrule Castle King Bulblin Key': 'Hyrule Castle Small Key',
    'Hyrule Castle Lantern Staircase Chest': 'Purple Rupee',
    'Hyrule Castle Main Hall Northeast Chest': 'Hyrule Castle Compass',
    'Hyrule Castle Main Hall Northwest Chest': 'Silver Rupee',
    'Hyrule Castle Main Hall Southwest Chest': 'Purple Rupee',
    'Hyrule Castle Southeast Balcony Tower Chest': 'Hyrule Castle Small Key',
    'Hyrule Castle Treasure Room Eighth Small Chest': 'Blue Rupee',
    'Hyrule Castle Treasure Room Fifth Chest': 'Purple Rupee',
    'Hyrule Castle Treasure Room Fifth Small Chest': 'Water Bombs (15)',
    'Hyrule Castle Treasure Room First Chest': 'Orange Rupee',
    'Hyrule Castle Treasure Room First Small Chest': 'Arrows (30)',
    'Hyrule Castle Treasure Room Fourth Chest': 'Bomblings (10)',
    'Hyrule Castle Treasure Room Fourth Small Chest': 'Arrows (20)',
    'Hyrule Castle Treasure Room Second Chest': 'Seeds (50)',
    'Hyrule Castle Treasure Room Second Small Chest': 'Green Rupee',
    'Hyrule Castle Treasure Room Seventh Small Chest': 'Yellow Rupee',
    'Hyrule Castle Treasure Room Sixth Small Chest': 'Red Rupee',
    'Hyrule Castle Treasure Room Third Chest': 'Silver Rupee',
    'Hyrule Castle Treasure Room Third Small Chest': 'Bombs (20)',
    'Hyrule Castle West Courtyard Central Small Chest': 'Red Rupee',
    'Hyrule Castle West Courtyard North Small Chest': 'Red Rupee',
    'Hyrule Field Amphitheater Owl Statue Chest': 'Orange Rupee',
    'Hyrule Field Amphitheater Owl Statue Sky Character': 'Progressive Sky Book',
    'Hyrule Field Amphitheater Poe': 'Poe Soul',
    'Ilia Memory Reward': 'Horse Call',
    'Isle of Riches Poe': 'Poe Soul',
    'Iza Helping Hand': 'Bomb Bag',
    'Iza Raging Rapids Minigame': 'Giant Bomb Bag',
    'Jovani 20 Poe Soul Reward': 'Jovani Bottle',
    'Jovani 60 Poe Soul Reward': 'Silver Rupee',
    'Jovani House Poe': 'Poe Soul',
    'Kakariko Gorge Double Clawshot Chest': 'Piece of Heart',
    'Kakariko Gorge Female Pill Bug': 'Female Pill Bug',
    'Kakariko Gorge Male Pill Bug': 'Male Pill Bug',
    'Kakariko Gorge Owl Statue Chest': 'Orange Rupee',
    'Kakariko Gorge Owl Statue Sky Character': 'Progressive Sky Book',
    'Kakariko Gorge Poe': 'Poe Soul',
    'Kakariko Gorge Spire Heart Piece': 'Piece of Heart',
    'Kakariko Graveyard Golden Wolf': 'Progressive Hidden Skill',
    'Kakariko Graveyard Grave Poe': 'Poe Soul',
    'Kakariko Graveyard Lantern Chest': 'Purple Rupee',
    'Kakariko Graveyard Male Ant': 'Male Ant',
    'Kakariko Graveyard Open Poe': 'Poe Soul',
    'Kakariko Inn Chest': 'Red Rupee',
    'Kakariko Village Bomb Rock Spire Heart Piece': 'Piece of Heart',
    'Kakariko Village Bomb Shop Poe': 'Poe Soul',
    'Kakariko Village Female Ant': 'Female Ant',
    'Kakariko Village Malo Mart Hawkeye': 'Hawkeye',
    'Kakariko Village Malo Mart Hylian Shield': 'Hylian Shield',
    'Kakariko Village Malo Mart Red Potion': 'Red Potion Shop',
    'Kakariko Village Malo Mart Wooden Shield': 'Wooden Shield',
    'Kakariko Village Watchtower Poe': 'Poe Soul',
    'Kakariko Watchtower Alcove Chest': 'Orange Rupee',
    'Kakariko Watchtower Chest': 'Purple Rupee',
    'Lake Hylia Alcove Poe': 'Poe Soul',
    'Lake Hylia Bridge Bubble Grotto Chest': 'Orange Rupee',
    'Lake Hylia Bridge Cliff Chest': 'Purple Rupee',
    'Lake Hylia Bridge Cliff Poe': 'Poe Soul',
    'Lake Hylia Bridge Female Mantis': 'Female Mantis',
    'Lake Hylia Bridge Male Mantis': 'Male Mantis',
    'Lake Hylia Bridge Owl Statue Chest': 'Orange Rupee',
    'Lake Hylia Bridge Owl Statue Sky Character': 'Progressive Sky Book',
    'Lake Hylia Bridge Vines Chest': 'Orange Rupee',
    'Lake Hylia Dock Poe': 'Poe Soul',
    'Lake Hylia Shell Blade Grotto Chest': 'Orange Rupee',
    'Lake Hylia Tower Poe': 'Poe Soul',
    'Lake Hylia Underwater Chest': 'Orange Rupee',
    'Lake Hylia Water Toadpoli Grotto Chest': 'Orange Rupee',
    'Lake Lantern Cave Eighth Chest': 'Bomblings (5)',
    'Lake Lantern Cave Eleventh Chest': 'Bomblings (10)',
    'Lake Lantern Cave End Lantern Chest': 'Piece of Heart',
    'Lake Lantern Cave Fifth Chest': 'Red Rupee',
    'Lake Lantern Cave Final Poe': 'Poe Soul',
    'Lake Lantern Cave First Chest': 'Bomblings (5)',
    'Lake Lantern Cave First Poe': 'Poe Soul',
    'Lake Lantern Cave Fourteenth Chest': 'Orange Rupee',
    'Lake Lantern Cave Fourth Chest': 'Arrows (10)',
    'Lake Lantern Cave Ninth Chest': 'Arrows (10)',
    'Lake Lantern Cave Second Chest': 'Yellow Rupee',
    'Lake Lantern Cave Second Poe': 'Poe Soul',
    'Lake Lantern Cave Seventh Chest': 'Red Rupee',
    'Lake Lantern Cave Sixth Chest': 'Orange Rupee',
    'Lake Lantern Cave Tenth Chest': 'Purple Rupee',
    'Lake Lantern Cave Third Chest': 'Red Rupee',
    'Lake Lantern Cave Thirteenth Chest': 'Seeds (50)',
    'Lake Lantern Cave Twelfth Chest': 'Purple Rupee',
    'Lakebed Temple Before Deku Toad Alcove Chest': 'Lakebed Temple Small Key',
    'Lakebed Temple Before Deku Toad Underwater Left Chest': 'Red Rupee',
    'Lakebed Temple Before Deku Toad Underwater Right Chest': 'Water Bombs (5)',
    'Lakebed Temple Big Key Chest': 'Lakebed Temple Big Key',
    'Lakebed Temple Central Room Chest': 'Lakebed Temple Map',
    'Lakebed Temple Central Room Small Chest': 'Arrows (20)',
    'Lakebed Temple Central Room Spire Chest': 'Red Rupee',
    'Lakebed Temple Chandelier Chest': 'Piece of Heart',
    'Lakebed Temple Deku Toad Chest': 'Progressive Clawshot',
    'Lakebed Temple Dungeon Reward': 'Progressive Fused Shadow',
    'Lakebed Temple East Lower Waterwheel Bridge Chest': 'Piece of Heart',
    'Lakebed Temple East Lower Waterwheel Stalactite Chest': 'Lakebed Temple Small Key',
    'Lakebed Temple East Second Floor Southeast Chest': 'Lakebed Temple Small Key',
    'Lakebed Temple East Second Floor Southwest Chest': 'Water Bombs (5)',
    'Lakebed Temple East Water Supply Clawshot Chest': 'Purple Rupee',
    'Lakebed Temple East Water Supply Small Chest': 'Water Bombs (10)',
    'Lakebed Temple Lobby Left Chest': 'Arrows (20)',
    'Lakebed Temple Lobby Rear Chest': 'Water Bombs (10)',
    'Lakebed Temple Morpheel': 'Morpheel Defeated',
    'Lakebed Temple Morpheel Heart Container': 'Heart Container',
    'Lakebed Temple Stalactite Room Chest': 'Water Bombs (10)',
    'Lakebed Temple Underwater Maze Small Chest': 'Water Bombs (5)',
    'Lakebed Temple West Lower Small Chest': 'Water Bombs (10)',
    'Lakebed Temple West Second Floor Central Small Chest': 'Red Rupee',
    'Lakebed Temple West Second Floor Northeast Chest': 'Water Bombs (15)',
    'Lakebed Temple West Second Floor Southeast Chest': 'Red Rupee',
    'Lakebed Temple West Second Floor Southwest Underwater Chest': 'Red Rupee',
    'Lakebed Temple West Water Supply Chest': 'Lakebed Temple Compass',
    'Lakebed Temple West Water Supply Small Chest': 'Water Bombs (10)',
    'Lanayru Field Behind Gate Underwater Chest': 'Orange Rupee',
    'Lanayru Field Bridge Poe': 'Poe Soul',
    'Lanayru Field Female Stag Beetle': 'Female Stag Beetle',
    'Lanayru Field Male Stag Beetle': 'Male Stag Beetle',
    'Lanayru Field Poe Grotto Left Poe': 'Poe Soul',
    'Lanayru Field Poe Grotto Right Poe': 'Poe Soul',
    'Lanayru Field Skulltula Grotto Chest': 'Orange Rupee',
    'Lanayru Field Spinner Track Chest': 'Piece of Heart',
    'Lanayru Ice Block Puzzle Cave Chest': 'Piece of Heart',
    'Lanayru Spring Back Room Lantern Chest': 'Piece of Heart',
    'Lanayru Spring Back Room Left Chest': 'Bombs (5)',
    'Lanayru Spring Back Room Right Chest': 'Blue Rupee',
    'Lanayru Spring East Double Clawshot Chest': 'Orange Rupee',
    'Lanayru Spring Underwater Left Chest': 'Blue Rupee',
    'Lanayru Spring Underwater Right Chest': 'Yellow Rupee',
    'Lanayru Spring West Double Clawshot Chest': 'Orange Rupee',
    'Links Basement Chest': 'Purple Rupee Links House',
    'Lost Woods Boulder Poe': 'Poe Soul',
    'Lost Woods Lantern Chest': 'Bombs (30)',
    'Lost Woods Waterfall Poe': 'Poe Soul',
    'North Castle Town Golden Wolf': 'Progressive Hidden Skill',
    'North Faron Woods Deku Baba Chest': 'Yellow Rupee',
    'Ordon Cat Rescue': 'Milk (half) (Sera Bottle)',
    'Ordon Ranch Grotto Lantern Chest': 'Purple Rupee',
    'Ordon Shield': 'Ordon Shield',
    'Ordon Spring Golden Wolf': 'Progressive Hidden Skill',
    'Ordon Sword': 'Progressive Master Sword',
    'Outside Arbiters Grounds Lantern Chest': 'Purple Rupee',
    'Outside Arbiters Grounds Poe': 'Poe Soul',
    'Outside Bulblin Camp Poe': 'Poe Soul',
    'Outside Lanayru Spring Left Statue Chest': 'Purple Rupee',
    'Outside Lanayru Spring Right Statue Chest': 'Orange Rupee',
    'Outside South Castle Town Double Clawshot Chasm Chest': 'Orange Rupee',
    'Outside South Castle Town Female Ladybug': 'Female Ladybug',
    'Outside South Castle Town Fountain Chest': 'Orange Rupee',
    'Outside South Castle Town Golden Wolf': 'Progressive Hidden Skill',
    'Outside South Castle Town Male Ladybug': 'Male Ladybug',
    'Outside South Castle Town Poe': 'Poe Soul',
    'Outside South Castle Town Tektite Grotto Chest': 'Orange Rupee',
    'Outside South Castle Town Tightrope Chest': 'Orange Rupee',
    'Palace of Twilight Big Key Chest': 'Palace of Twilight Big Key',
    'Palace of Twilight Central First Room Chest': 'Palace of Twilight Small Key',
    'Palace of Twilight Central Outdoor Chest': 'Palace of Twilight Small Key',
    'Palace of Twilight Central Tower Chest': 'Palace of Twilight Small Key',
    'Palace of Twilight Collect Both Sols': 'Progressive Master Sword',
    'Palace of Twilight East Wing First Room East Alcove Chest': 'Piece of Heart',
    'Palace of Twilight East Wing First Room North Small Chest': 'Purple Rupee',
    'Palace of Twilight East Wing First Room West Alcove Chest': 'Purple Rupee',
    'Palace of Twilight East Wing First Room Zant Head Chest': 'Palace of Twilight Small Key',
    'Palace of Twilight East Wing Second Room Northeast Chest': 'Purple Rupee',
    'Palace of Twilight East Wing Second Room Northwest Chest': 'Purple Rupee',
    'Palace of Twilight East Wing Second Room Southeast Chest': 'Palace of Twilight Small Key',
    'Palace of Twilight East Wing Second Room Southwest Chest': 'Palace of Twilight Map',
    'Palace of Twilight West Wing Chest Behind Wall of Darkness': 'Piece of Heart',
    'Palace of Twilight West Wing First Room Central Chest': 'Palace of Twilight Small Key',
    'Palace of Twilight West Wing Second Room Central Chest': 'Palace of Twilight Small Key',
    'Palace of Twilight West Wing Second Room Lower South Chest': 'Palace of Twilight Compass',
    'Palace of Twilight West Wing Second Room Southeast Chest': 'Orange Rupee',
    'Palace of Twilight Zant': 'Zant Defeated',
    'Palace of Twilight Zant Heart Container': 'Heart Container',
    'Plumm Fruit Balloon Minigame': 'Piece of Heart',
    'Renados Letter': 'Renados Letter',
    'Rutelas Blessing': 'Zora Armor',
    'STAR Prize 1': "Progressive Hero's Bow",
    'STAR Prize 2': "Progressive Hero's Bow",
    'Sacred Grove Baba Serpent Grotto Chest': 'Piece of Heart',
    'Sacred Grove Female Snail': 'Female Snail',
    'Sacred Grove Male Snail': 'Male Snail',
    'Sacred Grove Master Sword Poe': 'Poe Soul',
    'Sacred Grove Past Owl Statue Chest': 'Piece of Heart',
    'Sacred Grove Pedestal Master Sword': 'Progressive Master Sword',
    'Sacred Grove Pedestal Shadow Crystal': 'Shadow Crystal',
    'Sacred Grove Spinner Chest': 'Orange Rupee',
    'Sacred Grove Temple of Time Owl Statue Poe': 'Poe Soul',
    'Sera Shop Slingshot': 'Slingshot',
    'Skybook From Impaz': 'Progressive Sky Book',
    'Snowboard Racing Prize': 'Piece of Heart',
    'Snowpeak Above Freezard Grotto Poe': 'Poe Soul',
    'Snowpeak Blizzard Poe': 'Poe Soul',
    'Snowpeak Cave Ice Lantern Chest': 'Orange Rupee',
    'Snowpeak Cave Ice Poe': 'Poe Soul',
    'Snowpeak Freezard Grotto Chest': 'Orange Rupee',
    'Snowpeak Icy Summit Poe': 'Poe Soul',
    'Snowpeak Poe Among Trees': 'Poe Soul',
    'Snowpeak Ruins Ball and Chain': 'Ball and Chain',
    'Snowpeak Ruins Blizzeta': 'Blizzeta Defeated',
    'Snowpeak Ruins Blizzeta Heart Container': 'Heart Container',
    'Snowpeak Ruins Broken Floor Chest': 'Piece of Heart',
    'Snowpeak Ruins Chapel Chest': 'Snowpeak Ruins Bedroom Key',
    'Snowpeak Ruins Chest After Darkhammer': 'Snowpeak Ruins Ordon Goat Cheese',
    'Snowpeak Ruins Courtyard Central Chest': 'Bombs (5)',
    'Snowpeak Ruins Dungeon Reward': 'Progressive Mirror Shard',
    'Snowpeak Ruins East Courtyard Buried Chest': 'Red Rupee',
    'Snowpeak Ruins East Courtyard Chest': 'Snowpeak Ruins Small Key',
    'Snowpeak Ruins Ice Room Poe': 'Poe Soul',
    'Snowpeak Ruins Lobby Armor Poe': 'Poe Soul',
    'Snowpeak Ruins Lobby Chandelier Chest': 'Piece of Heart',
    'Snowpeak Ruins Lobby East Armor Chest': 'Yellow Rupee',
    'Snowpeak Ruins Lobby Poe': 'Poe Soul',
    'Snowpeak Ruins Lobby West Armor Chest': 'Red Rupee',
    'Snowpeak Ruins Mansion Map': 'Snowpeak Ruins Map',
    'Snowpeak Ruins Northeast Chandelier Chest': 'Snowpeak Ruins Small Key',
    'Snowpeak Ruins Ordon Pumpkin Chest': 'Snowpeak Ruins Ordon Pumpkin',
    'Snowpeak Ruins West Cannon Room Central Chest': 'Red Rupee',
    'Snowpeak Ruins West Cannon Room Corner Chest': 'Bombs (5)',
    'Snowpeak Ruins West Courtyard Buried Chest': 'Snowpeak Ruins Small Key',
    'Snowpeak Ruins Wooden Beam Central Chest': 'Red Rupee',
    'Snowpeak Ruins Wooden Beam Chandelier Chest': 'Snowpeak Ruins Small Key',
    'Snowpeak Ruins Wooden Beam Northwest Chest': 'Snowpeak Ruins Compass',
    'South Faron Cave Chest': 'Yellow Rupee',
    'Talo Sharpshooting': 'Piece of Heart',
    'Telma Invoice': 'Invoice',
    'Temple of Time Armogohma': 'Armogohma Defeated',
    'Temple of Time Armogohma Heart Container': 'Heart Container',
    'Temple of Time Armos Antechamber East Chest': 'Temple of Time Small Key',
    'Temple of Time Armos Antechamber North Chest': 'Red Rupee',
    'Temple of Time Armos Antechamber Statue Chest': 'Piece of Heart',
    'Temple of Time Big Key Chest': 'Temple of Time Big Key',
    'Temple of Time Chest Before Darknut': 'Purple Rupee',
    'Temple of Time Darknut Chest': 'Progressive Dominion Rod',
    'Temple of Time Dungeon Reward': 'Progressive Mirror Shard',
    'Temple of Time First Staircase Armos Chest': 'Temple of Time Map',
    'Temple of Time First Staircase Gohma Gate Chest': 'Arrows (30)',
    'Temple of Time First Staircase Window Chest': 'Red Rupee',
    'Temple of Time Floor Switch Puzzle Room Upper Chest': 'Red Rupee',
    'Temple of Time Lobby Lantern Chest': 'Temple of Time Small Key',
    'Temple of Time Moving Wall Beamos Room Chest': 'Temple of Time Compass',
    'Temple of Time Moving Wall Dinalfos Room Chest': 'Piece of Heart',
    'Temple of Time Poe Above Scales': 'Poe Soul',
    'Temple of Time Poe Behind Gate': 'Poe Soul',
    'Temple of Time Scales Gohma Chest': 'Purple Rupee',
    'Temple of Time Scales Upper Chest': 'Red Rupee',
    'Uli Cradle Delivery': 'Progressive Fishing Rod',
    'Upper Zoras River Female Dragonfly': 'Female Dragonfly',
    'Upper Zoras River Poe': 'Poe Soul',
    'West Hyrule Field Female Butterfly': 'Female Butterfly',
    'West Hyrule Field Golden Wolf': 'Progressive Hidden Skill',
    'West Hyrule Field Helmasaur Grotto Chest': 'Orange Rupee',
    'West Hyrule Field Male Butterfly': 'Male Butterfly',
    'Wooden Statue': 'Wooden Statue',
    'Wooden Sword Chest': 'Progressive Master Sword',
    'Wrestling With Bo': 'Iron Boots',
    'Zoras Domain Chest Behind Waterfall': 'Red Rupee',
    'Zoras Domain Chest By Mother and Child Isles': 'Yellow Rupee',
    'Zoras Domain Extinguish All Torches Chest': 'Purple Rupee',
    'Zoras Domain Light All Torches Chest': 'Purple Rupee',
    'Zoras Domain Male Dragonfly': 'Male Dragonfly',
    'Zoras Domain Mother and Child Isle Poe': 'Poe Soul',
    'Zoras Domain Underwater Goron': 'Bomb Bag',
    'Zoras Domain Waterfall Poe': 'Poe Soul',
}
